<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Yogeshs-MBP" ignored="2" name="Create Customer API" tests="4" failures="1" timestamp="2021-11-24T22:39:03 CET" time="5.172" errors="0">
  <testcase name="validateCreateCustomerAPIWithValidSecretKey" time="3.01" classname="APITestCases.CreateCustomerPostReqTest"/>
  <testcase name="validateCreateCustomerAPIWithValidSecretKey" time="0.668" classname="APITestCases.CreateCustomerPostReqTest"/>
  <testcase name="validateCreateCustomerAPIWithValidSecretKey" time="0.612" classname="APITestCases.CreateCustomerPostReqTest"/>
  <testcase name="deleteCustomer" time="0.635" classname="APITestCases.DeleteCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at APITestCases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:27)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase name="@AfterSuite tearDown" time="0.0" classname="SetupPackage.base">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDown -->
  <testcase name="@BeforeSuite setup" time="0.0" classname="SetupPackage.base">
    <ignored/>
  </testcase> <!-- @BeforeSuite setup -->
</testsuite> <!-- Create Customer API -->
